prep-javascript-arrays exercise - Adrian Guzman
adrian-guzman-301/prep-0622-code-solutions pull request #12
Opened 2022-06-15 01:54 UTC by adrian-guzman-301

![prep javascript arrays](https://user-images.githubusercontent.com/98074427/173719675-62e56188-fe4f-4c3e-bce2-5da48f452f94.png)

2022-06-15 22:13 UTC, thebearingedge requested changes

2022-06-15 22:13 UTC, thebearingedge commented on prep-javascript-arrays/main.js
> +const thirdElement = 'javascript';
Hi Adrian, you can access elements of an array by their index.

```js
var firstElement = languages[0];
var thirdElement = languages[2];
```

2022-06-15 22:13 UTC, thebearingedge commented on prep-javascript-arrays/main.js
> +console.log('the length of the array is', length);
You can get the length of an array with its `length` property.

```js
var length = languages.length;
```

2022-06-15 22:13 UTC, thebearingedge commented on prep-javascript-arrays/main.js
> +console.log('the last element of the array is', lastElement);
For this part the goal is to subtract `1` from `length` and use the result as the index into the `languages` array.

2022-06-16 05:14 UTC, adrian-guzman-301 commented on prep-javascript-arrays/main.js
> +console.log('the last element of the array is', lastElement);
![prep javascript arrays resubmission](https://user-images.githubusercontent.com/98074427/173996306-15c785e8-16ae-4d81-9c75-6848566ffa83.png)

2022-06-16 23:50 UTC, merged